# Image Recognition with ResNet50

### Import Data and Libraries

In [39]:
!pip install keras

In [40]:
import numpy as np

# image is an object with methods for processing image data
from keras.preprocessing import image

# Import the pre-trained ResNet50 machine learning model
from tensorflow.keras.applications import resnet50

In [41]:
# Instantiate the model
modelResNet50 = resnet50.ResNet50()

In [42]:
theImage = image.load_img('./bird.jpg', target_size=(224,224))

### Image Preprocessing

In [43]:
# Convert from image data to numpy array
theImageData = image.img_to_array(theImage)

# Pixels will have values ranging from 0 to 255
# 0 is black
# 255 is white
print(theImageData)


[[[225. 236. 242.]
  [225. 236. 242.]
  [225. 236. 242.]
  ...
  [233. 238. 242.]
  [233. 238. 242.]
  [233. 238. 242.]]

 [[225. 236. 242.]
  [225. 236. 242.]
  [225. 236. 242.]
  ...
  [233. 238. 242.]
  [233. 238. 242.]
  [233. 238. 242.]]

 [[225. 236. 242.]
  [225. 236. 242.]
  [225. 236. 242.]
  ...
  [233. 238. 242.]
  [233. 238. 242.]
  [233. 238. 242.]]

 ...

 [[237. 238. 240.]
  [237. 238. 240.]
  [237. 238. 240.]
  ...
  [ 92. 147.   1.]
  [105. 144.  25.]
  [111. 129.  55.]]

 [[237. 238. 240.]
  [237. 238. 240.]
  [237. 238. 240.]
  ...
  [103. 145.  19.]
  [109. 136.  41.]
  [108. 117.  70.]]

 [[237. 238. 240.]
  [237. 238. 240.]
  [237. 238. 240.]
  ...
  [129. 144.  39.]
  [120. 130.  57.]
  [109. 108.  80.]]]


In [44]:
# Exapnd the dimensions of the image data
theImageData = np.expand_dims(theImageData, axis=0)

### Classify the Image

In [45]:
# Predict the classes of the subject of the iamge
predictions = modelResNet50.predict(theImageData)

In [46]:
# Retrieve the predicted class and corresponding probabilities
# for the image
predictedClasses = resnet50.decode_predictions(predictions, top=10)

In [47]:
# Print the list of classes
print("This is image is:")

for classID, className, probability in predictedClasses[0]:
  print("Class is {} with probability {}".format(className, probability))

This is image is:
Class is spotlight with probability 0.396220862865448
Class is pinwheel with probability 0.20655770599842072
Class is sulphur-crested_cockatoo with probability 0.12055265158414841
Class is electric_fan with probability 0.041055817157030106
Class is hair_slide with probability 0.04105213284492493
Class is jay with probability 0.014902664348483086
Class is magpie with probability 0.014740721322596073
Class is mushroom with probability 0.01265310775488615
Class is fountain with probability 0.011951387859880924
Class is kite with probability 0.011855204589664936
